version: "3.9"

services:
  api:
    image: nepalankit/fastapi
    ports:
      - "80:8000"

    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_CONNECTION_URI=${DATABASE_CONNECTION_URI}
      - DATABASE_SECRET_KEY=${DATABASE_SECRET_KEY}
      - DATABASE_ALGORITHM=${DATABASE_ALGORITHM}
      - DATABASE_ACCESS_TOKEN_EXPIRE_MINUTES=${DATABASE_ACCESS_TOKEN_EXPIRE_MINUTES}
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
